### ISSUE TITLE
It doesn't work properly for me.

### ISSUE THREAD

**Issue by Virgula0** [mehulj94/Radium-Keylogger#3]
I don't know why.......
 I encode in base 64 all information, ftp user, server (but not ip because I use 000webhost like server so I encode the dns of the ftp server), email and password....
When I launch it appears None wrote in the console but when launched it seems working... Program sends me the connection information cookie etc on my email, after 300 words it also send me keylogs... but it doesn't send screenshots and after the former logs successfully sent it doesn't send nothing anymore. if I restart the pc it doesn't work...
Why?
Can you explain me?

Edit:

it works only if I run .py file.... if I use pyinstaller to make exe and I try to run it doesn't work and I changed all vraiables interested with the exact name of exe.... but nothing....

**Comment by sameh-malak** [comment]
i've the same problem

**Comment by dunkelite** [comment]
HELP!!! :(
 Why am I getting this error?

Traceback (most recent call last):
  File "C:\Users\dunkelite\Desktop\New folder (4)\Radium-Keylogger-master\Radiumkeylogger.py", line 51, in <module>
    passkey = base64.b64decode("zachlavine")  #Password to connect to GMAIL smtp server
  File "C:\Python27\lib\base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by dunkelite** [comment]
LAG 
I just noticed if I reached the 300 keystrokes  my computer LAGS while sending the logs on my email although I have a powerful pc. How to fix this? Sorry for my bad English. Thanks :)

**Comment by diebolo** [comment]
Hello, I have the same problem, but with that last edit do you mean that it works fully if you run the py file or runs as you described?
